name: ioncoin
version: v3.1.99-master
summary:   peer-to-peer network based digital currency
description: |
  ION is an MIT licensed,
  open source, blockchain-based cryptocurrency with 
  ultra fast transactions, low fees, high network decentralization, and
  Zero Knowledge cryptography proofs for industry-leading
  transaction anonymity. 
  
  Wiki (Ionomy):   https://github.com/ioncoincore/ion/wiki
  Wiki (IonomyCE): https://github.com/ioncoincore/ion/wiki
  
  Technical documentaion: https://techdoc.ioncoin.org
  
  Whitepaper: https://ionomy.com/en/whitepaper
  
  Technical whitepaper: 
    https://github.com/ionomy/ion/wiki/ION-Technical-Whitepaper
  
  Get source code from Github: https://github.com/ioncoincore/ion.git
  
  Chat with Support on Discord: https://discord.gg/vuZn7gC
  
  Contact us on social networks and forums
    Instagram: https://t.me/ionomy
    Twitter:   https://twitter.com/ionomics
    Reddit:    https://www.reddit.com/r/ionomy/
    Facebook:  https://facebook.com/ionomy

grade: devel
confinement: strict
icon: src/qt/res/src/ion.svg
apps:
  daemon:
    command: iond
    plugs: [network, network-bind, network-status, home, removable-media]
    desktop: iond.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-testnet:
    command: iond --testnet
    plugs: [network, network-bind, network-status, home, removable-media]
    desktop: iond_testnet.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-regtest:
    command: iond --regtest
    desktop: iond_regtest.desktop
    plugs: [network, network-bind, network-status, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: desktop-launch ion-qt
    plugs: [network, network-bind, unity7, desktop, desktop-legacy, wayland, x11]
    desktop: ion.desktop
  cli:
    command: ion-cli
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  tx:
    command: ion-tx

parts:
  ion:
    source: https://github.com/cevap/ion
    source-type: git
    source-tag: master
    plugin: autotools
    # We don't want to copy the full blockchain every time that the snap is   
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    override-build: git apply $SNAPCRAFT_STAGE/default_data_dir.patch
    build-packages:
      - curl
      - wget
      - g++
      - autoconf
      - automake
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      - libgmp-dev
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Files from the build host were migrated into the snap to satisfy dependencies that would otherwise not be met. This feature will be removed in a future release thats why we need to include them here
      - libxcursor-dev
      - libxinerama-dev
      - libxrandr-dev
      - libatk1.0-dev
      #- libgdk2.0-cil
      - libgtk2.0-dev
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    override-build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
      make install
    prime:
      - -*
  patches:
    source: snap/local/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
